name: Publish Docker image on FLUIDOS Docker Hub

on:
  push:
    tags: [ 'v*.*.*' ]
    branches:
      - main

env:
  IMAGE_BASE_NAME: fluidos-metaorchestrator

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Check out code
        uses: actions/checkout@v4
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-fluidos-mbmo-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-fluidos-mbmo-buildx-
      - name: Login to Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build (and Publish) fluidos-metaorchestrator image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_BASE_NAME }}:latest
            # ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_BASE_NAME }}:$GITHUB_SHA
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
